currentVersion = "0.1.3"
latestVersionDownloadURL = "https://www.dl.dropboxusercontent.com/s/6oq5yy1nsd3tytm/version.txt?dl=0"
changeLogDownloadURL = "https://www.dl.dropboxusercontent.com/s/bbobhm5mbxkzbqt/changelog.txt?dl=0"
latestPackageDownloadURL = "https://www.dl.dropboxusercontent.com/s/a9azyv1wvwf1phh/latest.7z?dl=0"
programFilesPath = "E:\UnlockPdf"
programName = "(Un)Lock Pdf"
