overwriteWithoutWarning = false
offerDesktopShortcut = true
offerStartMenuShortcut = true
offerLaunchAfterInstall = true
displayLicense = true
requireLicenseAcceptance = true
displayUrl = true
displayCopyright = true
displayVersion = true
installMVWUpdater = true

latestVersionDownloadURL = "https://dl.dropboxusercontent.com/s/utjud3e7d3jkzqu/version.txt?dl=0"
changeLogDownloadURL = "https://www.dl.dropboxusercontent.com/s/s2h9l65g0cd6ton/changelog.txt?dl=0"
latestPackageDownloadURL = "https://dl.dropboxusercontent.com/s/xhv2cujwn1smxmi/latest.7z?dl=0"

url = "https://www.steveoh.io"
copyRight = "2023 Steve Oh"
version = "1.0.0"
programName = "Test Program"
programExecutable = "aseprite.exe"

[[userEnvironmentVariables]]
var = "TEST_USER_ENV_VAR"
value = "test_user_env_var_value"

[[userEnvironmentVariables]]
var = "TEST_USER_ENV_VAR_2"
value = "test_user_env_var_value_2"

[[systemEnvironmentVariables]]
var = "TEST_SYSTEM_ENV_VAR"
value = "test_system_env_var_value"

[[systemEnvironmentVariables]]
var = "TEST_SYSTEM_ENV_VAR_2"
value = "test_system_env_var_value_2"

[[autoStartPrograms]]
name = "test_auto_start_program"
path = "C:/Program Files/Microsoft Office/root/Office16/OUTLOOK.EXE"
arguments = ""

[[moveFileSteps]]
source = "files/test.txt"
destination = "new/test1.txt"

[[moveDirectorySteps]]
source = "folder"
destination = ""

[[license]]
text = "This is a test license"
acceptanceText = "I accept this license"

[[license]]
text = "This is a test license 2"
acceptanceText = "I accept this license 2"