currentVersion = "1.0.0"
latestVersionDownloadURL = "https://dl.dropboxusercontent.com/s/utjud3e7d3jkzqu/version.txt?dl=0"
changeLogDownloadURL = "https://www.dl.dropboxusercontent.com/s/s2h9l65g0cd6ton/changelog.txt?dl=0"
latestPackageDownloadURL = "https://dl.dropboxusercontent.com/s/xhv2cujwn1smxmi/latest.7z?dl=0"
programFilesPath = "C:\Users\Owner\Desktop\testinstall"
programName = "Test Program"
